name: Windows-CI (static)

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows
            os: windows-latest
    env:
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgJsonGlob: "**/vcpkg.json"
        vcpkgDirectory: "${{ github.workspace }}/vcpkg"
        vcpkgGitCommitId: "962e5e39f8a25f42522f51fffc574e05a3efd26b"
    - name: Install simdutf
      run: |
        $VCPKG_ROOT/vcpkg install simdutf:x64-windows-static
      shell: bash
    - name: Configure
      run:  cmake -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x86-windows-static -B build
    - name: Build 
      run: cmake --build build --verbose