name: Linux-CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
        fail-fast: false
        matrix:
          include:
            - name: Linux
              os: ubuntu-latest
    env:
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgJsonGlob: "**/vcpkg.json"
        vcpkgDirectory: "${{ github.workspace }}/vcpkg"
        vcpkgGitCommitId: "d0d081b3fc3680ce8ced2a88f9a7784884b679da"
    - name: Install simdutf
      run: |
        $VCPKG_ROOT/vcpkg install simdutf
      shell: bash
    - name: Configure
      run:  cmake -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake -B build
    - name: Build 
      run: cmake --build build --verbose